name: dog_api
description: A new Flutter project.


environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.4

  dogs:
    path: features/dogs
  core:
    path: libraries/core
  network:
    path: libraries/network
  widgets:
    path: libraries/widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true